import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BadgeCheck, ChevronRight, Heart, Minus, Plus, RotateCcw, ShieldCheck, Star, Truck } from "lucide-react";
import { StoreHeader } from "@/components/store-header";
import { catalog, formatXof } from "@/lib/catalog";

export function generateStaticParams() { return catalog.map(({slug})=>({slug})); }

export default async function ProductPage({ params }: { params: Promise<{slug:string}> }) {
  const {slug}=await params; const product=catalog.find((item)=>item.slug===slug); if(!product) notFound();
  return <div><StoreHeader/><main className="product-page"><div className="breadcrumbs"><Link href="/">Accueil</Link><ChevronRight/><Link href="/catalogue">Catalogue</Link><ChevronRight/><span>{product.category}</span></div><section className="product-detail"><div className="detail-gallery"><div className="detail-main"><Image priority fill sizes="(max-width: 800px) 100vw, 52vw" src={product.image} alt={product.name}/><span>{product.tag}</span></div><div className="detail-thumbs"><button className="active" aria-label="Vue principale"><Image fill src={product.image} alt=""/></button><button aria-label="Détail matière"><Image fill src={catalog[4].image} alt=""/></button></div></div><div className="detail-copy"><p className="seller-line">{product.maker} · {product.location} <BadgeCheck/></p><h1>{product.name}</h1><div className="detail-rating"><span><Star/> {product.rating}</span><a href="#avis">{product.reviews} avis</a><button aria-label="Ajouter aux favoris"><Heart/> Enregistrer</button></div><strong className="detail-price">{formatXof(product.price)}</strong><p className="detail-description">Une pièce réalisée en petite série par des artisans béninois. Les légères variations de teinte et de forme rendent chaque exemplaire unique.</p><div className="variant-block"><label>Couleur <strong>Indigo profond</strong></label><div><button className="swatch indigo" aria-label="Indigo profond"/><button className="swatch clay" aria-label="Argile"/><button className="swatch cream" aria-label="Écru"/></div></div><div className="purchase-row"><div className="quantity"><button aria-label="Diminuer"><Minus/></button><span>1</span><button aria-label="Augmenter"><Plus/></button></div><Link className="buy-button" href="/panier">Ajouter au panier</Link></div><div className="delivery-note"><Truck/><div><strong>Livraison à Cotonou</strong><span>1 500 F · estimée entre vendredi et samedi</span></div><button>Changer</button></div><ul className="detail-assurances"><li><ShieldCheck/>Paiement Mobile Money protégé</li><li><RotateCcw/>Retour sous 7 jours selon éligibilité</li><li><BadgeCheck/>Vendeur vérifié par Gbéto</li></ul></div></section><section className="story-panel"><p className="eyebrow">Derrière le produit</p><h2>Un geste transmis,<br/>une matière vivante.</h2><p>{product.maker} travaille en petite série et privilégie les matières disponibles localement. Votre commande contribue directement à la rémunération de l’atelier.</p></section></main></div>;
}
